---

vormetric_component: ""
vormetric_operation: ""
vormetric_item: ""
vormetric_task_file_name: "{{ vormetric_operation }}_{{ ansible_system }}_{{ vormetric_component }}.yml"
vormetric_script_mode: false
vormetric_result_name: "result"

