---

libertybase_component: ""
libertybase_operation: ""
libertybase_task_file_name: "{{ libertybase_operation }}_{{ ansible_system }}_{{ libertybase_component }}.yml"
libertybase_script_mode: false
libertybase_result_name: ""
libertybase_item: ""
libertybase_res_name: ""
libertybase_layer: ""
libertybase_xml_file: ""
libertybase_ref: ""
libertybase_appli: ""
libertybase_dest_path: "/apps/toolboxes/web/ManageDeployEarWas/DeployEarWas/livrables"
libertybase_xml_filename: ""
libertybase_archive_filename: ""
libertybase_xml_src_path: ""
libertybase_archive_src_path: "{{ libertybase_xml_src_path }}"
libertybase_force_deploy: "no"


