---

wasbase_component: ""
wasbase_operation: ""
wasbase_task_file_name: "{{ wasbase_operation }}_{{ ansible_system }}_{{ wasbase_component }}.yml"
wasbase_script_mode: false
wasbase_item: ""
wasbase_result_name: ""
wasbase_ref: ""
wasbase_appli: ""
wasbase_dest_path: "/apps/toolboxes/web/ManageDeployEarWas/DeployEarWas/livrables"
wasbase_xml_filename: ""
wasbase_archive_filename: ""
wasbase_xml_src_path: ""
wasbase_archive_src_path: "{{ wasbase_xml_src_path }}"
wasbase_force_deploy: "no"



