---

sqlserver_component: ""
sqlserver_operation: ""
sqlserver_task_file_name: "{{ sqlserver_operation }}_{{ ansible_system }}_{{ sqlserver_component }}.yml"
sqlserver_script_mode: false
sqlserver_result_name: ""


