---

controlm_component: ""
controlm_operation: ""
controlm_task_file_name: "{{ controlm_operation }}_{{ ansible_system }}_{{ controlm_component }}.yml"
controlm_script_mode: false
controlm_result_name: ""
controlm_agent_name: "Default"
controlm_agentaccount: "ctmagent" 

